### ISSUE TITLE
Adopt the official Elm code style and use Elm format to format + enforce this style

### ISSUE THREAD

**Issue by lpil** [jameshopkins/webapptest#43]
Formatters are much nicer than linters because you write any crappy code you want, and it neatens it up for you every time you hit save :D

https://github.com/avh4/elm-format

**Comment by jameshopkins** [comment]
Yep. Completely agree. Initially noted in https://github.com/jameshopkins/webapptest/pull/19#discussion_r86224281 and created the issue at https://github.com/jameshopkins/webapptest/issues/32

**Comment by charypar** [comment]
I've started using that in Atom. It works fine, but produces very... airy code - lots of new lines and empty lines :) I assume that's what the style guide says, but not sure I'm a fan...

**Comment by lpil** [comment]
yeah, it's very vertical. Still, after a little adjustment period you don't really notice it, and then you never have to think/argue about style ever again,

*Every* language should have a formatter.

**Comment by jameshopkins** [comment]
A little bit of work required here, to mention the use of `elm-format` in our docs and the need to use it in your IDE, all of which can go under 'Dev setup' or similar

**Comment by charypar** [comment]
Would be nice to also enforce a check in CI that refuses code not matching the style

**Comment by jameshopkins** [comment]
Yep, completely agree
